import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../style/globals.css";
import TanstackProvider from "@module/_core/app/component/TanstackProvider";
import AppWrapper from "@module/_core/app/component/AppWrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap"
                    rel="stylesheet"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Google+Sans:wght@400;500;700&display=swap"
                    rel="stylesheet"
                />
                <meta
                    name="viewport"
                    content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=no"
                />
            </head>
            <body className="font-sans">
                <TanstackProvider>
                    <AppWrapper>{children}</AppWrapper>
                </TanstackProvider>
            </body>
        </html>
    );
}
